### PR TITLE
Finish dinner menu

### PR DESCRIPTION
**Pull request by breezjirasak**
I already add dinner menu to README.md and also add my name

### CODE REVIEW

**Comment by reviseUC73** [comment]
nice try bro

**Comment by reviseUC73** [comment]
jubjub breezy

**Comment by teenteennnii** [comment]
look nice.

**Comment by natekrth** [comment]
Looks good

**Comment by breezjirasak** [comment]
Approve merge into master

**Comment by teenteennnii** [comment]
+1

**Pull request merged**
