### PR TITLE
Finish Breakfast Menu

### PR DESCRIPTION
**Pull request by natekrth**
Add breakfast table menu add link to Breakfast section in README.md

### CODE REVIEW

**Comment by teenteennnii** [comment]
it look goods.

**Comment by breezjirasak** [comment]
It look very well.

**Comment by reviseUC73** [comment]
nice nice

**Comment by breezjirasak** [comment]
+1

**Comment by natekrth** [comment]
Merge Approve

**Comment by teenteennnii** [comment]
+1

**Pull request merged**
